name: QA

on:
  push:
    branches:
      - dev
      - stage
      - main
  pull_request:
    branches:
      - dev
      - stage
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: "test-encryption-key-for-ci-123456789"
      SENTRY_DSN: "test-sentry-dsn-for-ci-123456789"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install MariaDB Connector/C
        run: sudo apt-get update && sudo apt-get install -y libmariadb-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Node.js dependencies
        run: |
          if [ -f package.json ]; then npm install; fi

      - name: Run Python tests
        run: python run_tests.py all

      - name: Run mypy
        run: |
          if [ -f requirements.txt ]; then pip install mypy; fi
          mypy --explicit-package-bases lib settings.py

      - name: Run npm tests
        run: npm test

      - name: TypeScript type check
        run: npx tsc --project ./config/tsconfig.cicd.json --noEmit
